#!/usr/bin/python3
import sys
from num2words import num2words

def main():
    args=sys.argv
    args=args[1:]
    if len(args)==0:
        exit(1)
    o=num2words(int(args[0]))
    return o

if __name__=="__main__":
    print(main())